Refactored HeadersDsl and added disable option for headers
spring-projects-experimental/spring-security-kotlin-dsl pull request #11
Opened 2019-11-28 21:35 UTC by d-stoll

- Refactored the HeadersDsl to use HeadersConfigurer and its properties.

 - The individual header configurations are now applied directly to the fields of HeadersConfigurer.

 - Added a custom disable option for all headers where Spring Security allows custom deactivation.

- Added tests that check the individual deactivation of headers.

2019-11-28 21:48 UTC, d-stoll commented
Hey @eleftherias,

although the pull request goes beyond the issue itself, I think the changes make sense in this context. Imo we can adopt large parts of the actual Spring Security Dsl methods and only change the way they are called. For example via delegated properties.

The changes unfortunately break the current pattern.

2019-12-02 15:11 UTC, eleftherias requested changes
Thank you for the PR @d-stoll.

Unfortunately the new configuration method that you are suggesting is incompatible with the Kotlin DSL.
We need the configuration options to be retrieved in a single method because they depend on each other.

Consider this example:
```
@EnableWebSecurity
class FrameOptionsDisabledAndDenyConfig : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http {
            headers {
                defaultsDisabled = true
                frameOptions {
                    disable()
                    deny = true
                }
            }
        }
    }
}
```

The desired behaviour is for the frame options header to be disabled, however because `deny=true` was set after then the frame options header is re-enabled.

When using the Java configuration this is not possible because `disable()` returns the `HeadersConfigurer` and does not allow any further chaining.
However we cannot enforce that restriction in the Kotlin DSL. That is why we use the `get()` method to determine precedence instead of using only the order in which each configuration was called.
The `disable()` method should take precedence over any other configuration that enables a feature.

I have also left a couple more comments inline.

2019-12-02 15:11 UTC, eleftherias commented on src/main/kotlin/org/springframework/security/dsl/config/builders/servlet/headers/CacheControlDsl.kt
> +    fun disable() {
Please add a Javadoc to all `disable()` methods.

2019-12-02 15:11 UTC, eleftherias commented on src/main/kotlin/org/springframework/security/dsl/config/builders/servlet/headers/CacheControlDsl.kt
>   * @author Eleftheria Stein
Optionally, if you would like to, you can add your name to the list of authors for all the classes that you have updated.

2019-12-02 19:59 UTC, d-stoll commented
I get your point, but I'm not so sure about the current syntax for deactivating headers.

Lets take your example:
```Kotlin
headers {
   frameOptions {
      disable()
      deny = true
   }
}
```

If you assume that the desired behavior works here, it would confuse me as a developer that parts of my code are simply ignored. Wouldn't the following syntax make more sense?

```Kotlin
headers {
   frameOptions.disable()
}
```
or/and some sort of infix (maybe with an enum)
```Kotlin
headers disable frameOptions
```

With this variant a further configuration is avoided and thus also confusion on the part of the developer. I know this is exactly the syntax of Spring Security, but I think it's the only one that makes sense. Then we would not have to use the `get()` method and are able to reuse the configuration objects from Spring Security.

I was just a little bothered by the fact that some things are kind of declared exactly the same way they are declared in the original Dsl. I couldn't help but try to reuse it.

However, that is only a suggestion. For all I care, we can also simply implement your variant.

2019-12-12 17:37 UTC, eleftherias commented
@d-stoll 
Regarding the `get()` method, there are other situations, aside from `disable()`, where the configuration options depend on each other.
One example that I can think of is `sameOrigin` and `deny` in the `FrameOptionsDsl`.
Therefore, I think it is useful to have a method that determines which configuration to apply after all the options have been specified.

> Wouldn't the following syntax make more sense?
```
headers {
   frameOptions.disable()
}
```

I agree that this syntax is more clear.
How would you go about implementing this? It would be great if you submit an example of the source code implementing this syntax.

2020-03-05 22:14 UTC, eleftherias commented
Fixed in 3b4f759386714f4a35593ec0705e8bca4aad5e7c.

2020-03-05 22:14 UTC, closed without merging